export const stateCapital={
	name1:'state',
	name2:'captial',
	data:{
		"Andhra Pradesh": "Hyderabad",
		"Arunachal Pradesh": "Itanagar",
		"Assam": "Dispur",
		"Bihar": "Patna",
		"Chhattisgarh": "Raipur",
		"Goa": "Panaji",
		"Gujarat": "Gandhinagar",
		"Haryana": "Chandigarh",
		// "Himachal Pradesh": "Shimla",
		// "Jharkhand": "Ranchi",
		// "Karnataka": "Bengaluru",
		// "Kerala": "Thiruvananthapuram",
		// "Madhya Pradesh": "Bhopal",
		// "Maharashtra": "Mumbai",
		// "Manipur": "Imphal",
		// "Meghalaya": "Shillong",
		// "Mizoram": "Aizawl",
		// "Nagaland": "Kohima",
		// "Odisha": "Bhubaneswar",
		// "Punjab": "Chandigarh",
		// "Rajasthan": "Jaipur",
		// "Sikkim": "Gangtok",
		// "Tamil Nadu": "Chennai",
		// "Telangana": "Hyderabad",
		// "Tripura": "Agartala",
		// "Uttar Pradesh": "Lucknow",
		// "Uttarakhand": "Dehradun",
		// "West Bengal": "Kolkata"
	  }
}

export const playWithFlags={
	name1:'Country',
	name2:'Flags',
	data:{
		"Andorra": "https://www.countryflags.io/AD/shiny/64.png",
		"United Arab Emirates": "https://www.countryflags.io/AE/shiny/64.png",
		"Afghanistan": "https://www.countryflags.io/AF/shiny/64.png",
		"Antigua and Barbuda": "https://www.countryflags.io/AG/shiny/64.png",
		"Anguilla": "https://www.countryflags.io/AI/shiny/64.png",
		"Albania": "https://www.countryflags.io/AL/shiny/64.png",
		"Armenia": "https://www.countryflags.io/AM/shiny/64.png",
		"Netherlands Antilles": "https://www.countryflags.io/AN/shiny/64.png",
		"Angola": "https://www.countryflags.io/AO/shiny/64.png",
		"Antarctica": "https://www.countryflags.io/AQ/shiny/64.png",
		"Argentina": "https://www.countryflags.io/AR/shiny/64.png",
		// "American Samoa": "AS",
		// "Austria": "AT",
		// "Australia": "AU",
		// "Aruba": "AW",
		// "Åland Islands": "AX",
		// "Azerbaijan": "AZ",
		// "Bosnia and Herzegovina": "BA",
		// "Barbados": "BB",
		// "Bangladesh": "BD",
		// "Belgium": "BE",
		// "Burkina Faso": "BF",
		// "Bulgaria": "BG",
		// "Bahrain": "BH",
		// "Burundi": "BI",
		// "Benin": "BJ",
		// "Saint Barthélemy": "BL",
		// "Bermuda": "BM",
		// "Brunei Darussalam": "BN",
		// "Bolivia": "BO",
		// "Bonaire, Sint Eustatius and Saba": "BQ",
		// "Brazil": "BR",
		// "Bahamas": "BS",
		// "Bhutan": "BT",
		// "Bouvet Island": "BV",
		// "Botswana": "BW",
		// "Belarus": "BY",
		// "Belize": "BZ",
		// "Canada": "CA",
		// "Central African Republic": "CF",
		// "Congo": "CG",
		// "Switzerland": "CH",
		// "Côte D'Ivoire": "CI",
		// "Cook Islands": "CK",
		// "Chile": "CL",
		// "Cameroon": "CM",
		// "China": "CN",
		// "Colombia": "CO",
		// "Costa Rica": "CR",
		// "Cuba": "CU",
		// "Cape Verde": "CV",
		// "Curaçao": "CW",
		// "Christmas Island": "CX",
		// "Cyprus": "CY",
		// "Czech Republic": "CZ",
		// "Germany": "DE",
		// "Djibouti": "DJ",
		// "Denmark": "DK",
		// "Dominica": "DM",
		// "Dominican Republic": "DO",
		// "Algeria": "DZ",
		// "Ecuador": "EC",
		// "Estonia": "EE",
		// "Egypt": "EG",
		// "Western Sahara": "EH",
		// "Eritrea": "ER",
		// "Spain": "ES",
		// "Ethiopia": "ET",
		// "Finland": "FI",
		// "Fiji": "FJ",
		// "Faroe Islands": "FO",
		// "France": "FR",
		// "Gabon": "GA",
		// "United Kingdom": "GB",
		// "Grenada": "GD",
		// "Georgia": "GE",
		// "French Guiana": "GF",
		// "Guernsey": "GG",
		// "Ghana": "GH",
		// "Gibraltar": "GI",
		// "Greenland": "GL",
		// "Gambia": "GM",
		// "Guinea": "GN",
		// "Guadeloupe": "GP",
		// "Equatorial Guinea": "GQ",
		// "Greece": "GR",
		// "Guatemala": "GT",
		// "Guam": "GU",
		// "Guinea-Bissau": "GW",
		// "Guyana": "GY",
		// "Hong Kong": "HK",
		// "Honduras": "HN",
		// "Croatia": "HR",
		// "Haiti": "HT",
		// "Hungary": "HU",
		// "Indonesia": "ID",
		// "Ireland": "IE",
		// "Israel": "IL",
		// "Isle of Man": "IM",
		// "India": "IN",
		// "British Indian Ocean Territory": "IO",
		// "Iraq": "IQ",
		// "Iran, Islamic Republic Of": "IR",
		// "Iceland": "IS",
		// "Italy": "IT",
		// "Jersey": "JE",
		// "Jamaica": "JM",
		// "Jordan": "JO",
		// "Japan": "JP",
		// "Kenya": "KE",
		// "Kyrgyzstan": "KG",
		// "Cambodia": "KH",
		// "Kiribati": "KI",
		// "Comoros": "KM",
		// "Saint Kitts And Nevis": "KN",
		// "Korea, Democratic People's Republic Of": "KP",
		// "Korea, Republic of": "KR",
		// "Kuwait": "KW",
		// "Cayman Islands": "KY",
		// "Kazakhstan": "KZ",
		// "Lao People's Democratic Republic": "LA",
		// "Lebanon": "LB",
		// "Saint Lucia": "LC",
		// "Liechtenstein": "LI",
		// "Sri Lanka": "LK",
		// "Liberia": "LR",
		// "Lesotho": "LS",
		// "Lithuania": "LT",
		// "Luxembourg": "LU",
		// "Latvia": "LV",
		// "Libya": "LY",
		// "Morocco": "MA",
		// "Monaco": "MC",
		// "Moldova, Republic of": "MD",
		// "Montenegro": "ME",
		// "Saint Martin": "MF",
		// "Madagascar": "MG",
		// "Marshall Islands": "MH",
		// "Macedonia, the Former Yugoslav Republic Of": "MK",
		// "Mali": "ML",
		// "Myanmar": "MM",
		// "Mongolia": "MN",
		// "Macao": "MO",
		// "Northern Mariana Islands": "MP",
		// "Martinique": "MQ",
		// "Mauritania": "MR",
		// "Montserrat": "MS",
		// "Malta": "MT",
		// "Mauritius": "MU",
		// "Maldives": "MV",
		// "Malawi": "MW",
		// "Mexico": "MX",
		// "Malaysia": "MY",
		// "Mozambique": "MZ",
		// "Namibia": "NA",
		// "New Caledonia": "NC",
		// "Niger": "NE",
		// "Norfolk Island": "NF",
		// "Nigeria": "NG",
		// "Nicaragua": "NI",
		// "Netherlands": "NL",
		// "Norway": "NO",
		// "Nepal": "NP",
		// "Nauru": "NR",
		// "Niue": "NU",
		// "New Zealand": "NZ",
		// "Oman": "OM",
		// "Panama": "PA",
		// "Peru": "PE",
		// "French Polynesia": "PF",
		// "Papua New Guinea": "PG",
		// "Philippines": "PH",
		// "Pakistan": "PK",
		// "Poland": "PL",
		// "Saint Pierre And Miquelon": "PM",
		// "Pitcairn": "PN",
		// "Puerto Rico": "PR",
		// "Palestine, State of": "PS",
		// "Portugal": "PT",
		// "Palau": "PW",
		// "Paraguay": "PY",
		// "Qatar": "QA",
		// "Réunion": "RE",
		// "Romania": "RO",
		// "Serbia": "RS",
		// "Russian Federation": "RU",
		// "Rwanda": "RW",
		// "Saudi Arabia": "SA",
		// "Solomon Islands": "SB",
		// "Seychelles": "SC",
		// "Sudan": "SD",
		// "Sweden": "SE",
		// "Singapore": "SG",
		// "Saint Helena": "SH",
		// "Slovenia": "SI",
		// "Svalbard And Jan Mayen": "SJ",
		// "Slovakia": "SK",
		// "Sierra Leone": "SL",
		// "San Marino": "SM",
		// "Senegal": "SN",
		// "Somalia": "SO",
		// "Suriname": "SR",
		// "South Sudan": "SS",
		// "Sao Tome and Principe": "ST",
		// "El Salvador": "SV",
		// "Sint Maarten": "SX",
		// "Syrian Arab Republic": "SY",
		// "Swaziland": "SZ",
		// "Turks and Caicos Islands": "TC",
		// "Chad": "TD",
		// "French Southern Territories": "TF",
		// "Togo": "TG",
		// "Thailand": "TH",
		// "Tajikistan": "TJ",
		// "Tokelau": "TK",
		// "Timor-Leste": "TL",
		// "Turkmenistan": "TM",
		// "Tunisia": "TN",
		// "Tonga": "TO",
		// "Turkey": "TR",
		// "Trinidad and Tobago": "TT",
		// "Tuvalu": "TV",
		// "Taiwan, Republic Of China": "TW",
		// "Tanzania, United Republic of": "TZ",
		// "Ukraine": "UA",
		// "Uganda": "UG",
		// "United States Minor Outlying Islands": "UM",
		// "United States": "US",
		// "Uruguay": "UY",
		// "Uzbekistan": "UZ",
		// "Holy See (Vatican City State)": "VA",
		// "Saint Vincent And The Grenadines": "VC",
		// "Venezuela, Bolivarian Republic of": "VE",
		// "Virgin Islands, British": "VG",
		// "Virgin Islands, U.S.": "VI",
		// "Vietnam": "VN",
		// "Vanuatu": "VU",
		// "Wallis and Futuna": "WF",
		// "Samoa": "WS",
		// "Yemen": "YE",
		// "Mayotte": "YT",
		// "South Africa": "ZA",
		// "Zambia": "ZM",
		// "Zimbabwe": "ZW"
		}
}

export const factAboutIndia={
	name1:'National Symbol',
	name2:'Name',
	data:{
		'Anthem':'Jana Gana Mana',
		'Song':'Vande Mataram',
		'Currency':'Indian Rupee',
		'River':'Ganges',
		'Flower':'Indian Lotus',
		'Fruit ':'Mango',
		'Tree':'Banyan',
		'Animal':'Bengal tiger',
		'Flag':'Tiranga',
		'motto':'सत्यमेव जयते',
		'bird':'Indian peacock'
	}
}